# Dependabot config
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "tuesday"
      time: "11:25" # UTC
    groups:
      all:
        patterns:
          - "*"
    #   remix:
    #     patterns:
    #       - "@remix-run/*"
    #   react:
    #     patterns:
    #       - "react"
    #       - "react-dom"
    #       - "@types/react"
    #       - "@types/react-dom"
